### ISSUE TITLE
[ Week 0 ] 0주차 워크북 미션

### ISSUE THREAD

**Issue by seunghyeonKang** [DS-UMC-7th/UMC-7th-Box#1]
### 🛠 Mission

html, css 학습

### 📝 To-do

- [x] 정렬 기능(`display`) 활용하여 Navbar 만들어보기
- [x] (Navbar 반응형 만들기)
- [x] 정렬 기능(`flex`, `grid`) 활용하여 구조 잡기

### 🔍 접근 방법

- `grid-template-columns/row`, `grid-column/row`를 사용하여 그리드 간격 조절
> display
> flex
> grid
