### ISSUE TITLE
[ Week 6 ] 6주차 워크북 미션

### ISSUE THREAD

**Issue by seunghyeonKang** [DS-UMC-7th/UMC-7th-Box#12]
### 🛠 Mission

- [실습] Context-API로 to-do list 리펙토링
- [미션1] 회원가입 / 로그인 API 연결
- [미션2] QueryParameter 활용 검색 기능 구현

### 📝 To-do

- [x] Context-API의 useContext를 활용하여 전역 상태 관리하기
- [x] AccessToken과 RefreshToken를 활용한 로그인 방식 학습하기
- [x] QueryParameter를 활용하여 검색 기능 구현하기
- [ ] Debounce 활용하기
- [ ] Skeleton UI 만들어보기

### 🔍 접근 방법

1. 공부
