### ISSUE TITLE
[ Week 8 ] 8주차 워크북 미션

### ISSUE THREAD

**Issue by seunghyeonKang** [DS-UMC-7th/UMC-7th-Box#15]
### 🛠 Mission

미션 1. ToDo List 구현 (useEffect 활용)
미션 2. ToDoList 구현 (Tanstack-Query 활용)
미션 3. 기존 영화 사이트 리팩토링 진행!

### 📝 To-do

- [ ] ToDo List 구현 (useEffect 활용)
- [ ] ToDoList 구현 (Tanstack-Query 활용)
- [ ] 기존 영화 사이트 리팩토링 진행

### 🔍 접근 방법

- ToDo List 구현 (useEffect 활용)
- ToDoList 구현 (Tanstack-Query 활용)
- 기존 영화 사이트 리팩토링 진행
