### ISSUE TITLE
[ Week 1 ] 1주차 워크북 미션

### ISSUE THREAD

**Issue by seunghyeonKang** [DS-UMC-7th/UMC-7th-Box#2]
### 🛠 Mission

JavaScript 학습 - To-do List 페이지 만들기

### 📝 To-do

- [x] [html, css] 제목, 해야 할 일을 작성할 수 있는 칸, 해야 할 일/해낸 일을 표시하는 UI 만들기
- [x] [JavaScript] 해야 할 일을 작성할 수 있는 input 컴포넌트에 내용을 작성하고, ENTER를 입력하면 해야 할 일에 작성한 할 일이 추가 되도록 기능 추가하기
- [x] [JavaScript] 해야 할 일의 완료를 누르면 해당할 일이 해낸 일로 이동하도록 기능 추가하기
- [x] [JavaScript] 해낸 일의 삭제를 누르면 삭제되도록 기능 추가하기

### 🔍 접근 방법

- 시멘틱 요소 정리하기
- 요소를 추가/수정하는 메소드 사용하기
