### ISSUE TITLE
[ Week 2 ] 2주차 워크북 미션

### ISSUE THREAD

**Issue by seunghyeonKang** [DS-UMC-7th/UMC-7th-Box#4]
### 🛠 Mission

1. To-do List 만들기
2. 영화 컴포넌트 만들기

### 📝 To-do

- [x] [실습] To-do List 만들며 useState 익히기
- [x] [미션1] To-do List 컴포넌트 분리하기
- [x] [미션1] To-do List CSS 추가하기
- [x] [미션2] 영화 API 사용하여 영화 컴포넌트 만들기
- [x] [미션2] 마우스 hover인 경우 효과 추가하기

### 🔍 접근 방법

> props로 함수와 텍스트 등을 전달하여 컴포넌트 분리하기
> map 함수를 이용하여 영화 컴포넌트 반복하기
