### ISSUE TITLE
[ Week 3 ] 3주차 워크북 미션

### ISSUE THREAD

**Issue by seunghyeonKang** [DS-UMC-7th/UMC-7th-Box#6]
### 🛠 Mission

영화 사이트 제작하기

### 📝 To-do

- [x] navbar 구현하기
- [x] sidebar 구현하기
- [x] 화면 이동 구현하기 - React Router
- [x] 카테고리별 영화 리스트 불러오기
- [x] Styled-Components를 활용하여 스타일링하기

### 🔍 접근 방법

1. 컴포넌트 재사용하기
2. Styled-Component 활용하기
3. 폴더 구조 정리하기
4. React Router 활용하기
5. useEffect 활용해서 api 연결하기
