### ISSUE TITLE
[ Week 4 ] 4주차 워크북 미션

### ISSUE THREAD

**Issue by seunghyeonKang** [DS-UMC-7th/UMC-7th-Box#8]
### 🛠 Mission

영화 사이트(3주차 미션) 리펙토링 및 영화 상세 페이지 추가

### 📝 To-do

- [x] Custom Hook을 이용한 영화 사이트(3주차 미션) 리펙토링
- [x] 영화 상세 페이지 추가하기
- [x] Custom Hook을 이용하여 loading 및 error 처리하기
- [x] env 파일 관리하기

### 🔍 접근 방법

- axios를 이용하여 api 연동한 부분을 loading과 error를 추가하여 Custom Hook을 만든다.
- 영화 이미지를 background로 넣고 그라데이션을 이용하여 영화 정보의 가시성을 높인다.
- 감독/출연 부분은 flex, wrap을 이용하여 적절하게 배치한다.
